data_shards = 2
parity_shards = 1
redundant_groups = 0
redundant_nodes = 0

[encryption]
algorithm = "AES"
key = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

[compression]
algorithm = "snappy"

[meta]
type = "etcd"

[meta.config]
endpoints = ["http://127.0.0.1:2379"]
prefix = "someprefix"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:94b3:c0ff:fe47:313b]:9900"
namespace = "17093-1"
password = "future01"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:94b3:c0ff:fe47:313b]:9900"
namespace = "17094-1"
password = "future01"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:3c0d:23ff:fe58:98ef]:9900"
namespace = "17095-1"
password = "future01"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:3c0d:23ff:fe58:98ef]:9900"
namespace = "17096-1"
password = "future01"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:4863:b0ff:fe86:ed5a]:9900"
namespace = "17097-1"
password = "future01"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:4863:b0ff:fe86:ed5a]:9900"
namespace = "17098-1"
password = "future01"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:a8d9:daff:fedd:ef6f]:9900"
namespace = "17099-1"
password = "future01"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:a8d9:daff:fedd:ef6f]:9900"
namespace = "17100-1"
password = "future01"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:90f0:c1ff:fe5f:18eb]:9900"
namespace = "17101-1"
password = "future01"

[[groups]]

[[groups.backends]]
address = "[2a02:1802:5e:0:90f0:c1ff:fe5f:18eb]:9900"
namespace = "17102-1"
password = "future01"

