data_shards = 1
parity_shards = 1
redundant_groups = 0
redundant_nodes = 0
root = "/virtualroot"
socket = "/tmp/zstor.sock"
network = "Main"
wallet_secret = "SABDZC5WIRSR4A6T5JOVOYXTXKSGE6LBX7GD4CMNVHQK4WN5MEQNGRKB"
identity_id = 0
identity_mnemonic = "shop moral play negative liar lucky hub stock merge sea treat spare spray december media setup mean narrow combine merge mixture arm boy stem"
horizon_url = "https://my.horizon.server"
prometheus_port = 9100
zdb_data_dir_path = "/tmp/0-db/data"
max_zdb_data_dir_size = 256000
zdbfs_mountpoint = "/somewhere"

[encryption]
algorithm = "AES"
key = "0000000000000000000000000000000000000000000000000000000000000000"

[compression]
algorithm = "snappy"

[meta]
type = "zdb"

[meta.config]
prefix = "debug-prefix"

[meta.config.encryption]
algorithm = "AES"
key = "0101010101010101010101010101010101010101010101010101010101010101"

[[meta.config.backends]]
address = "127.0.0.1:9901"
namespace = "zstor-meta-1"

[[meta.config.backends]]
address = "127.0.0.1:9901"
namespace = "zstor-meta-2"

[[meta.config.backends]]
address = "127.0.0.1:9901"
namespace = "zstor-meta-3"

[[meta.config.backends]]
address = "127.0.0.1:9901"
namespace = "zstor-meta-4"

[[groups]]
[[groups.backends]]
address = "127.0.0.1:9901"
namespace = "zstor-backend-1"

[[groups.backends]]
address = "127.0.0.1:9901"
namespace = "zstor-backend-2"

